repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        exclude: node_modules
      - id: end-of-file-fixer
        exclude: node_modules
      - id: debug-statements
        exclude: node_modules
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/snakemake/snakefmt
    rev: 0.4.2
    hooks:
      - id: snakefmt
        language_version: python3
