channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy>=1.20
  - pip>=20.3.3
  - python=3.9
  - setuptools>=51.3.3
  - tectonic>=0.7.1
  - snakemake>=6.5.2
  - jinja2>=2.10
  - black>=19.9
  - conda-pack>=0.5.0
  - pip:
    - matplotlib>=3.3.3
    - nose>=1.3.7
    - parameterized>=0.8.1
    - pytest>=6.2.1
    - pytest-dependency>=0.5.1
    - pytest-env>=0.6.2
    - questionary>=1.9
    - tqdm>=4.56.0
