dependencies:
  - conda-forge::python>=3.9
  - conda-forge::pip>=21.0.1
  - conda-forge::tectonic>=0.11.0
  - conda-forge::mamba>=0.25.0
  - conda-forge::imagemagick>=7.1.0.27
  - conda-forge::python-graphviz>=0.19.1
  - conda-forge::jinja2>=3.0.3
  - conda-forge::pyyaml>=6.0
  - conda-forge::requests>=2.25.1
  - conda-forge::click>=8.0.4
  - conda-forge::cookiecutter>=2.1.1
  - bioconda::snakemake=7.15.2
