name: Notify cookiecutter-showyourwork

on:
  push:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          gh api repos/rodluger/cookiecutter-showyourwork/dispatches \
              --raw-field event_type=showyourwork_update
