name: paper

on:
  push:
    branches: [main]

jobs:
  paper:
    name: Build the paper
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults,bioconda
          channel-priority: strict
          activate-environment: cortex
          environment-file: environment.yml
          use-only-tar-bz2: true

      - name: Build the paper
        shell: bash -l {0}
        run: |
          snakemake -c1

      - name: Upload the paper
        uses: dfm/force-push-branch-action@v1
        with:
          branch-suffix: "-pdf"
          commit-message: "Committing automatically from GitHub Actions"
          path: |
            ms.pdf