name: paper

on:
  push:
    branches: [main]

jobs:
  paper:
    name: Build the paper
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache the repo
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: |
            $GITHUB_WORKSPACE/.cortex/data
            $GITHUB_WORKSPACE/tex
            $GITHUB_WORKSPACE/figures
            $GITHUB_WORKSPACE/tests
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ 
              hashFiles('$GITHUB_WORKSPACE/.cortex/data/*.json', '$GITHUB_WORKSPACE/tex/*', '$GITHUB_WORKSPACE/figures/*.py', '$GITHUB_WORKSPACE/tests/*.py') }}

      - name: Cache info
        shell: bash -l {0}
        run: |
          ls -lahtr $GITHUB_WORKSPACE/.cortex/data
          ls -lahtr $GITHUB_WORKSPACE/tex
          ls -lahtr $GITHUB_WORKSPACE/figures
          ls -lahtr $GITHUB_WORKSPACE/tests

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults,bioconda
          channel-priority: strict
          activate-environment: cortex
          environment-file: environment.yml

      - name: Generate the DAG
        shell: bash -l {0}
        run: |
          snakemake --dag | dot -Tpdf > dag.pdf

      - name: Build the paper
        shell: bash -l {0}
        run: |
          snakemake -c1

      - name: Upload the paper
        uses: dfm/force-push-branch-action@v1
        with:
          branch-suffix: "-pdf"
          commit-message: "Committing automatically from GitHub Actions"
          path: |
            ms.pdf
            dag.pdf