name: release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  generate_example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter packaging

      - name: Generate rodluger/showyourwork-example
        env:
          SLUG: rodluger/showyourwork-example
          REPO_ACTIVE: n
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SKIP_CI: n
          RUN_TESTS: n
        run: python showyourwork-workflow/workflow/scripts/new.py

      - name: Generate rodluger/showyourwork-template
        env:
          SLUG: rodluger/showyourwork-template
          REPO_ACTIVE: n
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SKIP_CI: y
          RUN_TESTS: n
        run: python showyourwork-workflow/workflow/scripts/new.py
