name: release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        required: true
        default: "patch"

jobs:
  showyourwork:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version
        uses: actions/github-script@v4
        id: bump
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release_type }}
        with:
          result-encoding: string
          script: |
            // Get all tags
            const tags = await github.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Get latest version
            var latest = [0, 0, 0];
            for (let i = 0; i < tags.data.length; i++) {
              const tag = tags.data[i].name;
              if (tag[0] == "v") {
                const version = tag.slice(1).split(".").map(x=>+x);
                if (version.length == 3) {
                  if (version[0] > latest[0]) {
                    latest = version;
                  } else if (version[0] == latest[0]) {
                    if (version[1] > latest[1]) {
                      latest = version;
                    } else if (version[1] == latest[1]) {
                      if (version[2] > latest[2]) {
                        latest = version;
                      }
                    }
                  }
                }
              }
            }

            // Bump the version
            var major = latest[0];
            var minor = latest[1];
            var patch = latest[2];
            const {RELEASE_TYPE} = process.env;
            if (RELEASE_TYPE == 'patch') {
              patch += 1;
            } else if (RELEASE_TYPE == 'minor') {
              patch = 0;
              minor += 1;
            } else if (RELEASE_TYPE == 'major') {
              patch = 0;
              minor = 0;
              major += 1;
            } else {
              core.setFailed('Invalid release type.');
            }

            // Push new docs link
            await exec.exec("sed", ["-i", "-E", `s|https://showyourwork.readthedocs.io/en/(v[0-9]+\.[0-9]+\.[0-9]+)|https://showyourwork.readthedocs.io/en/v${major}.${minor}.${patch}|g`, "README.md"]);
            await exec.exec("git", ["add", "README.md"]);
            await exec.exec("git", ["-c", "user.name='gh-actions", "-c", "user.email='gh-actions'", "commit", "-m", "update docs link"]);
            await exec.exec("git", ["push", "origin", "main"]);

            // Create release w/ new version
            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${major}.${minor}.${patch}`
            });

            // Return new version
            return `v${major}.${minor}.${patch}`;

      - name: Update template-minimal
        id: template-minimal
        if: steps.bump.outcome == 'success'
        shell: bash -l {0}
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git clone --recurse-submodules https://github.com/rodluger/showyourwork-template-minimal
          cd showyourwork-template-minimal/showyourwork
          git fetch --all --tags
          git checkout tags/"${{steps.bump.outputs.result}}"
          cd ..
          git add showyourwork
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "update showyourwork to ${{steps.bump.outputs.result}}"
          git push https://x-access-token:${ACCESS_TOKEN}@github.com/rodluger/showyourwork-template-minimal main
          echo "        with:" >> .github/workflows/showyourwork.yml
          echo "          article-cache-number: ${{steps.bump.outputs.result}}" >> .github/workflows/showyourwork.yml
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "update showyourwork to ${{steps.bump.outputs.result}}"
          git push --force https://x-access-token:${ACCESS_TOKEN}@github.com/rodluger/showyourwork-template-minimal-test main

      - name: Update template-full
        id: template-full
        if: steps.bump.outcome == 'success'
        shell: bash -l {0}
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git clone --recurse-submodules https://github.com/rodluger/showyourwork-template-full
          cd showyourwork-template-full/showyourwork
          git fetch --all --tags
          git checkout tags/"${{steps.bump.outputs.result}}"
          cd ..
          git add showyourwork
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "update showyourwork to ${{steps.bump.outputs.result}}"
          git push https://x-access-token:${ACCESS_TOKEN}@github.com/rodluger/showyourwork-template-full main
          echo "        with:" >> .github/workflows/showyourwork.yml
          echo "          article-cache-number: ${{steps.bump.outputs.result}}" >> .github/workflows/showyourwork.yml
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "update showyourwork to ${{steps.bump.outputs.result}}"
          git push --force https://x-access-token:${ACCESS_TOKEN}@github.com/rodluger/showyourwork-template-full-test main

      - name: Wait for builds to finish
        id: wait
        if: ((steps.template-minimal.outcome == 'success') && (steps.template-full.outcome == 'success'))
        shell: bash -l {0}
        run: |
          sleep 1s
