name: release_minor

on:
  workflow_dispatch:

env:
  RELEASE_TYPE: minor

jobs:
  showyourwork:
    runs-on: ubuntu-latest
    name: Minor release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version
        uses: actions/github-script@v4
        id: bump
        with:
          script: |
            // Get all tags
            const tags = github.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Get latest version
            var latest = [0, 0, 0];
            for ( let i = 0; i < tags.data.length; i++ ) {
              const tag = tags.data[i];
              if (tag[0] == "v") {
                const version = tag.slice(1).split(".");
                if (version.length == 3) {
                  if (version[0] > latest[0]) {
                    latest = version;
                  } else if (version[0] == latest[0]) {
                    if (version[1] > latest[1]) {
                      latest = version;
                    else if (version[1] == latest[1]) {
                      if (version[2] > latest[2]) {
                        latest = version;
                    }
                  }
                }
              }
            }

            // Bump the version
            const {RELEASE_TYPE} = process.env;
            if (RELEASE_TYPE == 'patch')
              latest[2] += 1;
            else if (RELEASE_TYPE == 'minor')
              latest[1] += 1;
            else if (RELEASE_TYPE == 'major')
              latest[0] += 1;
            else
              core.setFailed('Invalid release type.');

            // Create release w/ new version
            github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${latest}`,
            });
