name: showyourwork

on:
  push:
    branches: [main]

jobs:
  showyourwork:
    name: Build the paper
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache the repo
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: |
            .showyourwork/data
            tex
            figures
            tests
            ms.pdf
          key:
            ${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ 
              hashFiles(
                '.showyourwork/data/*.json', 
                'tex/*', 
                'figures/*.py', 
                'tests/*.py'
              ) }}

      - name: Cache info
        shell: bash -l {0}
        run: |
          ls -lahtr .showyourwork/data
          ls -lahtr tex
          ls -lahtr figures
          ls -lahtr tests

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults,bioconda
          channel-priority: strict
          activate-environment: showyourwork
          environment-file: environment.yml

      - name: Generate the DAG
        shell: bash -l {0}
        run: |
          snakemake --dag | dot -Tpdf > dag.pdf

      - name: Build the paper
        shell: bash -l {0}
        run: |
          snakemake -c1

      - name: Upload the paper
        uses: dfm/force-push-branch-action@v1
        with:
          branch-suffix: "-pdf"
          commit-message: "Committing automatically from GitHub Actions"
          path: |
            ms.pdf
            dag.pdf