name: showyourwork

on:
  push:
    branches: [main]

env:
  MAMBA_CACHE_NUMBER: 0
  SYW_CACHE_NUMBER: 3
  MAMBA_ENV: sywenv

jobs:

  # https://github.com/conda-incubator/setup-miniconda/issues/155#issuecomment-846598562
  setup-mamba:
    name: Setup mamba environment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Cache mamba environment
        id: cache-mamba
        uses: actions/cache@v2
        with:
          path: "${{ env.MAMBA_ENV }}.tar.gz"
          key:
            ${{ runner.os }}-${{ env.MAMBA_CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      
      - name: Setup mamba environment
        if: steps.cache-mamba.outputs.cache-hit != 'true'
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          auto-update-conda: false
          activate-environment: ${{ env.MAMBA_ENV }}
          environment-file: environment.yml
          auto-activate-base: false

      - name: Pack mamba environment
        if: steps.cache-mamba.outputs.cache-hit != 'true'
        run: |
          conda pack --force -n ${{ env.MAMBA_ENV }}

  showyourwork:
    name: Build the paper
    needs: [setup-mamba]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get mamba cache
        id: mamba-cache
        uses: actions/cache@v2
        with:
          path: "${{ env.MAMBA_ENV }}.tar.gz"
          key:
            ${{ runner.os }}-${{ env.MAMBA_CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Unpack mamba environment
        run: |
          mkdir -p "${{ env.MAMBA_ENV }}"
          tar -xzf "${{ env.MAMBA_ENV }}.tar.gz" -C "${{ env.MAMBA_ENV }}"
          source "${{ env.MAMBA_ENV }}/bin/activate"
          conda-unpack

      # https://github.com/actions/cache/issues/432#issuecomment-740376179
      - name: Generate random cache key
        id: random-cache-key
        run: head /dev/random -c 32 > random-cache-key

      - name: Cache showyourwork
        uses: actions/cache@v2
        with:
          path: |
            .cache
          key:
            ${{ runner.os }}-${{ env.SYW_CACHE_NUMBER }}-${{ hashFiles('random-cache-key') }}
          restore-keys:
            ${{ runner.os }}-${{ env.SYW_CACHE_NUMBER }}

      - name: Restore the cached figures and test results
        run: |
          source "${{ env.MAMBA_ENV }}/bin/activate"
          python .github/workflows/cache.py --restore
          ls -lahtr .cache
          ls -lahtr .cache/figures
          ls -lahtr .cache/tests

      - name: Build the paper
        run: |
          source "${{ env.MAMBA_ENV }}/bin/activate"
          ls -lahtr figures
          ls -lahtr tests
          snakemake -c1

      - name: Generate the DAG
        run: |
          source "${{ env.MAMBA_ENV }}/bin/activate"
          snakemake --dag | dot -Tpdf > dag.pdf

      - name: Update the cached figures and test results
        run: |
          source "${{ env.MAMBA_ENV }}/bin/activate"
          python .github/workflows/cache.py --update
          ls -lahtr .cache
          ls -lahtr .cache/figures
          ls -lahtr .cache/tests

      - name: Upload the paper
        uses: dfm/force-push-branch-action@v1
        with:
          branch-suffix: "-pdf"
          commit-message: "Automatic commit from GitHub Actions"
          path: |
            ms.pdf
            dag.pdf