name: showyourwork

on:
  push:
    branches: [main]

jobs:
  showyourwork:
    name: Build the paper
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache the repo
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: |
            .cache
          key:
            ${{ runner.os }}-${{ env.CACHE_NUMBER }}

      - name: Restore the cache
        shell: bash -l {0}
        run: |
          python .github/workflows/cache.py --restore

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults,bioconda
          channel-priority: strict
          activate-environment: showyourwork
          environment-file: environment.yml

      - name: Build the paper
        shell: bash -l {0}
        run: |
          snakemake -c1

      - name: Generate the DAG
        shell: bash -l {0}
        run: |
          snakemake --dag | dot -Tpdf > dag.pdf

      - name: Cache the figures and test results
        shell: bash -l {0}
        run: |
          python .github/workflows/cache.py --update

      - name: Upload the paper
        uses: dfm/force-push-branch-action@v1
        with:
          branch-suffix: "-pdf"
          commit-message: "Committing automatically from GitHub Actions"
          path: |
            ms.pdf
            dag.pdf