name: tests

on:
  repository_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TEST_BUILD_OUTCOME: ${{ github.event.client_payload.test_build_outcome }}"
      TEST_CACHE_OUTCOME: ${{ github.event.client_payload.test_cache_outcome }}"
      REPO: ${{ github.event.client_payload.repo }}"
      RUN_ID: ${{ github.event.client_payload.run_id }}"
    steps:
      - name: Test info
        run: |
          TEST_BUILD_OUTCOME="${TEST_BUILD_OUTCOME%\"}"
          TEST_CACHE_OUTCOME="${TEST_CACHE_OUTCOME%\"}"
          REPO="${REPO%\"}"
          RUN_ID="${RUN_ID%\"}"
          echo "::notice::Test details here: https://github.com/${REPO}/actions/runs/${RUN_ID}"
          [[ ${TEST_BUILD_OUTCOME} == "success" && ${TEST_CACHE_OUTCOME} == "success" ]] && exit 0 || exit 1
