name: test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Run tests
        id: tests
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}