name: tests

on:
  repository_dispatch:

jobs:
  receive:
    runs-on: ubuntu-latest
    env:
      BUILD_OUTCOME: ${{ github.event.client_payload.build_outcome }}"
    steps:
      - name: Receive test info
        run: |
          [[ ${BUILD_OUTCOME} == "success" ]] && exit 0 || exit 1
