name: dispatch

on:
  push:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter

      - name: Generate rodluger/showyourwork-sandbox
        env:
          SLUG: rodluger/showyourwork-sandbox
          REPO_ACTIVE: n
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SKIP_CI: n
          RUN_TESTS: y
        run: python showyourwork/new.py