name: tests

on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:

jobs:
  unit:
    if: github.event_name != 'pull_request_target'
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.9"

      - name: Install showyourwork
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[tests]"

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest tests/unit

  integration:
    if: github.event_name != 'pull_request_target'
    runs-on: ubuntu-latest
    name: Run integration tests
    concurrency: showyourwork-integration
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.9"

      - name: Install showyourwork
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[tests]"

      - name: Run local integration tests
        shell: bash -l {0}
        run: python -m pytest tests/integration

  remote:
    if: github.event_name == 'push'
    uses: dfm/showyourwork/.github/workflows/remote.yml@test-structure # FIXME
    secrets: inherit

  remote-pr:
    if: github.event_name == 'pull_request_target'
    environment: Integrate Pull Request
    uses: dfm/showyourwork/.github/workflows/remote.yml@test-structure # FIXME
    secrets: inherit
