name: dispatch

on:
  push:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Jinja2

      - name: Generate rodluger/showyourwork-sandbox
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SHA: ${{ github.sha }}
          SLUG: rodluger/showyourwork-sandbox
          REPO_ACTIVE: true
          MANUSCRIPT_TYPE: minimal
          RUN_TESTS: true
          AUTHOR: "Rodrigo Luger"
          README_MESSAGE: test
        run: python .github/workflows/generate.py
