name: dispatch

on:
  push:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter

      - name: Generate rodluger/showyourwork-sandbox
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPOSITORY: rodluger/showyourwork-sandbox
          ADD_CALLBACK: true
        run: bash .github/workflows/generate.sh
